# Generated by Django 5.0.2 on 2024-02-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0005_alter_userrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.CharField(choices=[(1, 'Adept'), (2, 'Writer'), (3, 'Artist'), (4, 'Erudite')], default='Adept', max_length=20),
        ),
    ]
