# Generated by Django 5.0.2 on 2024-02-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0006_alter_userrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.CharField(max_length=20),
        ),
    ]
