# Generated by Django 5.0.2 on 2024-02-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0008_note_priority_alter_userrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Norma l', 'Normal'), ('Low', 'Low'), ('None', 'None')], default='None', max_length=10),
        ),
    ]
