# Generated by Django 5.0.2 on 2024-02-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0009_alter_note_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Project', 'Project'), ('Hobby', 'Hobby'), ('Science', 'Science'), ('Health and Sport', 'Health and Sport'), ('Finances', 'Finances')], max_length=100)),
                ('note', models.ManyToManyField(blank=True, related_name='note', to='NOTEBOOK.note')),
            ],
        ),
    ]
