# Generated by Django 5.0.2 on 2024-02-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0010_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='NOTEBOOK.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Project', 'Project'), ('Hobby', 'Hobby'), ('Science', 'Science'), ('Health and Sport', 'Health and Sport'), ('Finances', 'Finances'), ('Other', 'Other')], max_length=100),
        ),
    ]
