# Generated by Django 5.0.2 on 2024-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0011_remove_category_note_note_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Project', 'Project'), ('Hobby', 'Hobby'), ('Science', 'Science'), ('Health and Sport', 'Health and Sport'), ('Finances', 'Finances'), ('Other', 'Other')], max_length=100, unique=True),
        ),
    ]
