# Generated by Django 5.0.2 on 2024-02-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0012_note_pinned_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'Work'), (2, 'Personal'), (3, 'Project'), (4, 'Hobby'), (5, 'Science'), (6, 'Health and Sport'), (7, 'Finances'), (8, 'Other')], max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='NOTEBOOK.category'),
        ),
    ]
