# Generated by Django 5.0.2 on 2024-02-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, default='Other', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='NOTEBOOK.category'),
        ),
    ]
