# Generated by Django 5.0.2 on 2024-02-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTEBOOK', '0016_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Project', 'Project'), ('Hobby', 'Hobby'), ('Science', 'Science'), ('Health and Sport', 'Health and Sport'), ('Finances', 'Finances'), ('Other', 'Other')], default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='NOTEBOOK.category'),
        ),
    ]
